### ISSUE TITLE
Support RD6012/RD6018/RD6024

### ISSUE THREAD

**Issue by wildekek** [wildekek/rdtech-esphome#5]
I'd love to support the other Riden power supply types and [it seems](https://github.com/Baldanos/rd6006) that the protocol is fairly similar:
```
        if self.type == 6012 or self.type == 6018 or self.type == 6024:
            print("RD6012, RD6018 or RD6024 detected")
            self.voltres = 100
            self.ampres = 100
        else:
            print("RD6006 or other detected")
            self.voltres = 100
            self.ampres = 1000
```
Unfortunately I do not have these units to test, and I feel uncomfortable releasing software for controlling a PSU that people use for charging LiPo batteries and other spicy components that I can't test IRL.

**Comment by chron0** [comment]
I do have the RD6018 and would like to install this to it to have it under esphome/hass control and be able to log long term data, especially for my lifepo4 battery bank top balance formation runs. So I could test this if it's already merged.

**Comment by wildekek** [comment]
Found the following differences between the models:
Model number:
60062
	Name: RD6006
	Voltage precision: 2
	Current precision: 3
	Max voltage: 60
	Max current: 6
60065
	Name: RD6006P
	Voltage precision: 3
	Current precision: 4
	Max voltage: 60
	Max current: 6
60121
	Name: RD6012
	Voltage precision: 2
	Current precision: 2
	Max voltage: 60
	Max current: 20
60181
	Name: RD6018
	Voltage precision: 2
	Current precision: 2
	Max voltage: 60
	Max current: 18


I'll try and make support for the other models in the near future. Could you help me test the RD6018 @chron0 ? I would like to know if the model number shows up correctly using the latest version of the main branch. I can then change some parameters and make it work, should be fairly simple.

**Comment by chron0** [comment]
I could give it a try, it's been a while since I pimped my riden (see https://odysee.com/@Apollo-NG:2/pimp-my-riden-1:1?r=9GPazzWhkRN7uXjT7tbgNuzpoZAF4G6Z&t=6064) but the next time i rotate back to it I could try this yaml config instead to test it for the rd6018 and will report back on it.

**Comment by bassclarinetl2** [comment]
I have a 6012 if you need a tester.

**Comment by Dom4n** [comment]
I have RD6018 with UniSoft firmware 1.41.1k, and I can confirm, that everything works after these changes are applied:

```diff
@@ -1,6 +1,6 @@
 substitutions:
-  device_name: "rd6006-controller"
-  device_friendly_name: "RD 6006"
+  device_name: "riden-rd6018"
+  device_friendly_name: "Riden RD6018"
   device_description: "Power Supply"
   time_timezone: "Europe/Amsterdam"
 
@@ -10,7 +10,7 @@
   comment: $device_description
   name_add_mac_suffix: false
   project:
-    name: "wildekek.rd6006-controller"
+    name: "wildekek.rd6018-controller"
     version: "1.3.2"
 
 esp8266:
@@ -160,7 +160,7 @@
     value_type: U_WORD
     accuracy_decimals: 3
     filters:
-      - multiply: 0.001
+      - multiply: 0.01
 
   - platform: modbus_controller
     modbus_controller_id: powersupply
@@ -385,7 +385,7 @@
     min_value: 0
     max_value: 6
     step: 0.001
-    multiply: 1000
+    multiply: 100
 
   - platform: modbus_controller
     modbus_controller_id: powersupply
@@ -411,7 +411,7 @@
     min_value: 0
     max_value: 6
     step: 0.01
-    multiply: 1000
+    multiply: 100
 
   # Date components are kept internal
   - platform: modbus_controller
```
I have tested all sensors except temperature external, because I never used it. Disconnected probe shows 65,625stC. 
Current is shown in 10mA steps, on UniSoft's fw this value is interpolated and accuracy is 1mA on display. This is not really a problem for me, but worth noting.

I think that second file in this repository for RD6018 should be best solution.

Thanks for Your work!

**Comment by wildekek** [comment]
Thanks for all your efforts to get other models tested and included!
Since the diff between the models is so small, the neatest solution imo is to make 1 file that supports all models. That way it is easier to update in the future. I think I can write something that checks the model once during startup and saves the accuracy/range values to EEPROM. I'll work on it a bit this week and will poke this thread when I have a testable version.

**Comment by wildekek** [comment]
> I'm not super familiar with esphome, but couldn't the lambda if x true false be simplified to just return the condition directly?
> 
> EDIT: Yes, you can `lambda: return X;` instead
I don't understand which code you're referring to and how this is related to this issue, help me.

**Comment by ShayBox** [comment]
https://github.com/wildekek/riden-esphome/blob/main/rd6006-controller.yaml#L321-L326

This format can be replaced with just `lambda: return X;`

**Comment by ShayBox** [comment]
Are you able to use lambdas in configuration variables? [global variables with lambdas](https://esphome.io/guides/automations.html#global-variables), the yaml substitutes are a good solution if not

**Comment by wildekek** [comment]
No, lambda's in configuration variables are not an option. I'm working on a pretty clean solution using substitutions like so:

```
substitutions:
  # Change this model to fit your particular one.
  # You can find it in Home Assistant as the device diagnostic "Model Name".
  model: "RD6006"
  device_name: "rd6006-controller"
  device_friendly_name: "RD 6006"
  device_description: "Power Supply"
  time_timezone: "Europe/Amsterdam"
  
  # Model specific settings (Don't change these!)
  RD6006_max_voltage: "60"
  RD6006_max_current: "6"
  RD6006_voltage_precision: "2"
  RD6006_current_precision: "3"

  RD6006P_max_voltage: "60"
  RD6006P_max_current: "6"
  RD6006P_voltage_precision: "3"
  RD6006P_current_precision: "4"

  RD6012_max_voltage: "60"
  RD6012_max_current: "12"
  RD6012_voltage_precision: "2"
  RD6012_current_precision: "2"

  RD6018_max_voltage: "60"
  RD6018_max_current: "18"
  RD6018_voltage_precision: "2"
  RD6018_current_precision: "2"

```
snip
```
max_value: ${${model}_max_voltage}
```
